-- Run this once in Supabase SQL Editor before deploying the Supabase version.
-- The votes table created during initial setup is empty and can be replaced.
drop table if exists public.sessions;
drop table if exists public.votes;

create table public.votes (
  id bigint generated by default as identity primary key,
  voter_id text not null,
  candidate_id integer not null,
  category text not null,
  request_id text not null,
  created_at timestamptz not null default now(),
  constraint votes_one_per_term unique (voter_id, category),
  constraint votes_request_once unique (voter_id, request_id)
);

create table public.sessions (
  token text primary key,
  voter_id text not null,
  expires bigint not null
);

create index votes_candidate on public.votes (candidate_id);
create index sessions_expires on public.sessions (expires);

alter table public.votes enable row level security;
alter table public.sessions enable row level security;

-- No public policies are intentional. Only the server-side secret key can read
-- voter emails, sessions, and individual votes.
